color0 #47464e
color1 #ffb4ab
color2 #c5c2f3
color3 #c7c4da
color4 #eeb6d7
color5 #c5c2f3
color6 #c7c4da
color7 #e5e1e5
color8 #928f99
color9 #ffb4ab
color10 #c5c2f3
color11 #c7c4da
color12 #eeb6d7
color13 #c5c2f3
color14 #c7c4da
color15 #e5e1e5

cursor                #e5e1e5
cursor_text_color     #131316
background            #131316
foreground            #e5e1e5
selection_foreground  #c8c5cf
selection_background  #47464e
active_border_color   #c5c2f3
inactive_border_color #47464e
url_color             #c5c2f3

active_tab_foreground   #2e2c53
active_tab_background   #c5c2f3
inactive_tab_foreground #c8c5cf
inactive_tab_background #47464e
cursor_trail_color      #c8c5cf
