[bar.default]
background_opacity = 0.29999999329447746
capsule = false
capsule_border = "outline"
capsule_radius = 10
capsule_thickness = 0.78
center = [
    "clock-main",
]
enabled = true
end = [
    "group:g2",
    "group:g1",
    "group:g3",
]
margin_edge = 2
margin_ends = 12
position = "top"
shadow = true
start = [
    "group:g4",
    "group:g5",
]
thickness = 36

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g1"
members = [
    "network",
    "volume",
    "battery",
]
opacity = 0.0
padding = 30.0
radius = 10.0
widget_spacing = 25

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g2"
members = [
    "audio_visualizer",
    "cpu",
    "ram",
]
opacity = 0.0
padding = 6.0
radius = 10.0

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g3"
members = [
    "tray",
    "control-center",
    "session",
]
opacity = 0.0
padding = 6.0
radius = 10.0
widget_spacing = 15

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g4"
members = [
    "launcher",
    "notifications",
]
opacity = 0.0
padding = 6.0
radius = 10.0

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
border = ""
enabled = true
fill = "surface"
id = "g5"
members = [
    "workspaces",
    "taskbar",
]
opacity = 1.0
padding = 10.0
radius = 10.0
widget_spacing = 25

[brightness]
enable_ddcutil = true
minimum_brightness = 0.19999999552965164
sync_all_monitors = true

[control_center]
show_session_button = true
show_shortcut_labels = false
sidebar = "compact"
sidebar_section = "compact"
width = 600

[control_center.calendar]
show_events_card = true
show_week_numbers = false

[desktop_widgets]
enabled = true
schema_version = 2
widget_order = [
    "media_main",
    "calendar_main",
]

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[desktop_widgets.widget.calendar_main]
box_height = 400.0
box_width = 380.0
cx = 270.0
cy = 796.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "calendar"

[desktop_widgets.widget.calendar_main.settings]
background = true
background_color = "surface"
background_opacity = 0.72
background_padding = 14.0
background_radius = 18.0
font_family = "Inter, Noto Sans CJK TC"
show_events = true
show_week_numbers = false

[desktop_widgets.widget.media_main]
box_height = 400.0
box_width = 224.0
cx = 208.0
cy = 348.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "media_player"

[desktop_widgets.widget.media_main.settings]
background = true
background_color = "surface"
background_opacity = 0.72
background_padding = 16.0
background_radius = 18.0
color = "on_surface"
hide_when_no_media = false
layout = "vertical"
shadow = true

[dock]
enabled = true
icon_size = 40
reserve_space = false
show_dots = true
smart_auto_hide = true

[notification]
background_opacity = 0.84
border = true
enable_daemon = true
layer = "top"
offset_x = 16
position = "top_right"
scale = 0.95
show_app_name = true

[osd.kinds]
keyboard_layout = false
lock_keys = false
media = false

[shell]
app_icon_colorize = false
button_borders = true
card_borders = true
clipboard_enabled = false
corner_radius_scale = 1.2
date_format = "%a, %b %d"
font_family = "Inter, Noto Sans CJK TC"
input_borders = true
popup_borders = true
popup_shadows = true
settings_window_translucent = true
time_format = "{:%H:%M}"

[shell.animation]
enabled = true
speed = 1.1

[shell.panel]
borders = true
clipboard_placement = "floating"
control_center_placement = "attached"
control_center_position = "top_right"
floating_layer = "overlay"
floating_offset = 10
launcher_placement = "floating"
launcher_position = "center"
list_item_background = false
open_near_click_control_center = true
session_placement = "attached"
shadow = true
transparency_mode = "glass"
wallpaper_placement = "attached"

[shell.shadow]
alpha = 0.42
direction = "down"

[theme]
builtin = "Tokyo-Night"
mode = "dark"
pure_black_dark = false
shell_mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[theme.templates]
builtin_ids = [
    "btop",
    "cava",
    "gtk3",
    "gtk4",
    "ghostty",
    "hyprland",
    "kitty",
    "qt",
]
community_ids = []

[wallpaper]
edge_smoothness = 0.25
enabled = true
fill_mode = "crop"
transition = [
    "fade",
    "zoom",
]
transition_duration = 900

[wallpaper.default]
path = "/home/abnertu/Pictures/Wallpapers/arch-building-with-girl-5.png"

[wallpaper.last]
path = "/home/abnertu/Pictures/Wallpapers/arch-building-with-girl-5.png"

[wallpaper.monitors.HDMI-A-1]
path = "/home/abnertu/Pictures/Wallpapers/arch-building-with-girl-5.png"

[widget.audio_visualizer]
color_2 = "tertiary"
mirrored = false
show_when_idle = true

[widget.battery]
display_mode = "graphic"

[widget.clock-main]
capsule = true
capsule_border = "outline"
capsule_fill = "surface_variant"
capsule_opacity = 0.42
capsule_padding = 16
font_scale = 0.95
format = "{:%a, %b %d  %H:%M}"
type = "clock"

[widget.control-center]
glyph = "hyprland"
icon_color = "tertiary"

[widget.cpu]
show_value = true
stat = "cpu_usage"
type = "sysmon"
visualization = "none"

[widget.launcher]
glyph = "apps-filled"

[widget.media-mini]
art_size = 18
capsule = true
capsule_opacity = 0.35
hide_artist = false
max_length = 170
min_length = 100
type = "media"

[widget.ram]
show_value = true
stat = "ram_pct"
type = "sysmon"
visualization = "none"

[widget.taskbar]
active_indicator_color = "primary"
active_opacity = 1.0
group_by_workspace = false
icon_scale = 1.2000000000000002
inactive_opacity = 0.78
item_spacing = 5
only_active_workspace = false
pinned = [
    "zen",
    "kitty",
    "thunar",
]
pinned_opacity = 0.55
show_active_indicator = true
show_all_outputs = false
show_window_title = true
taskbar_max_width = 520
type = "taskbar"
window_title_max_width = 80

[widget.tray]
drawer = true
drawer_columns = 5
drawer_item_size = 20.0

[widget.workspaces]
capsule = false
capsule_opacity = 0.45
label_source = "id"
max_label_chars = 2
show_icons = false
show_labels = true
style = "regular"
type = "workspaces"
