[bar.default]
background_opacity = 0.0
capsule = true
capsule_border = "outline"
capsule_radius = 26
capsule_thickness = 0.8999999836087227
center = []
end = [
    "clock",
    "tray",
    "group:g1",
]
margin_edge = 2
margin_ends = 14
shadow = false
start = [
    "group:g2",
    "workspaces",
]
thickness = 36

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
border = "outline"
enabled = true
fill = "surface_variant"
id = "g1"
members = [
    "notifications",
    "control-center",
    "session",
]
opacity = 1.0
padding = 14.0
widget_spacing = 14

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
border = "outline"
enabled = true
fill = "surface_variant"
id = "g2"
members = [
    "launcher",
    "wallpaper",
]
opacity = 1.0
padding = 14.0
widget_spacing = 14

[brightness]
enable_ddcutil = true
minimum_brightness = 0.19999999552965164
sync_all_monitors = true

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000006",
    "desktop-widget-0000000000000007",
]

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[desktop_widgets.widget.desktop-widget-0000000000000001]
box_height = 96.0
box_width = 1888.0
cx = 960.0
cy = 1020.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "audio_visualizer"

[desktop_widgets.widget.desktop-widget-0000000000000001.settings]
background = false
bands = 32
color_1 = "tertiary"
color_2 = "tertiary"
mirrored = true
show_when_idle = true

[desktop_widgets.widget.desktop-widget-0000000000000002]
box_height = 80.0
box_width = 128.0
cx = 1728.0
cy = 380.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "sysmon"

[desktop_widgets.widget.desktop-widget-0000000000000002.settings]
background = true
background_opacity = 1.0
color = "tertiary"
display = "gauge"
font_family = ""
gauge_layout = "horizontal"
shadow = true
show_label = true
stat = "cpu_usage"
stat2 = "cpu_temp"

[desktop_widgets.widget.desktop-widget-0000000000000003]
box_height = 80.0
box_width = 128.0
cx = 1728.0
cy = 492.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "sysmon"

[desktop_widgets.widget.desktop-widget-0000000000000003.settings]
background = true
background_opacity = 1.0
color = "tertiary"
display = "gauge"
font_family = ""
gauge_layout = "horizontal"
shadow = true
show_label = true
stat = "cpu_temp"
stat2 = "cpu_temp"

[desktop_widgets.widget.desktop-widget-0000000000000004]
box_height = 80.0
box_width = 128.0
cx = 1728.0
cy = 604.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "sysmon"

[desktop_widgets.widget.desktop-widget-0000000000000004.settings]
background = true
background_opacity = 1.0
color = "tertiary"
display = "gauge"
font_family = ""
gauge_layout = "horizontal"
shadow = true
show_label = true
stat = "gpu_usage"
stat2 = "cpu_temp"

[desktop_widgets.widget.desktop-widget-0000000000000005]
box_height = 80.0
box_width = 128.0
cx = 1728.0
cy = 716.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = -0.0
type = "sysmon"

[desktop_widgets.widget.desktop-widget-0000000000000005.settings]
background = true
background_opacity = 1.0
color = "tertiary"
display = "gauge"
font_family = ""
gauge_layout = "horizontal"
shadow = true
show_label = true
stat = "gpu_temp"
stat2 = "cpu_temp"

[desktop_widgets.widget.desktop-widget-0000000000000006]
box_height = 256.0
box_width = 480.0
cx = 288.0
cy = 204.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "media_player"

[desktop_widgets.widget.desktop-widget-0000000000000006.settings]
color = "tertiary"
layout = "horizontal"

[desktop_widgets.widget.desktop-widget-0000000000000007]
box_height = 240.0
box_width = 368.0
cx = 768.0
cy = 204.0
output = "HDMI-A-1"
placement_height = 1080.0
placement_width = 1920.0
rotation = 0.0
type = "clock"

[desktop_widgets.widget.desktop-widget-0000000000000007.settings]
background = true
background_color = "surface"
clock_style = "digital"
color = "tertiary"
shadow = true

[osd.kinds]
keyboard_layout = false
lock_keys = false
media = false

[shell]
clipboard_enabled = false

[shell.panel]
clipboard_position = "auto"
control_center_placement = "floating"
open_near_click_clipboard = true
open_near_click_control_center = true
open_near_click_session = true
session_placement = "floating"
wallpaper_placement = "floating"
wallpaper_position = "center"

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Moon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "soft"

[theme.templates]
builtin_ids = [
    "btop",
    "cava",
    "gtk3",
    "gtk4",
    "hyprland",
    "kitty",
    "qt",
]
community_ids = [
    "zen-browser",
    "bat",
    "discord",
    "lazygit",
    "steam",
    "hyprtoolkit",
]

[widget.clock]
format = "{:%D  %H:%M}"

[widget.control-center]
glyph = "hyprland"

[widget.launcher]
glyph = "apps-filled"
